export const RECEIVE_ALL_STOCKS = 'RECEIVE_ALL_STOCKS';
export const ERROR_RECEIVE_ALL_STOCKS = 'ERROR_RECEIVE_ALL_STOCKS';

export const RECEIVE_PRICE = 'RECEIVE_PRICE';
export const ERROR_RECEIVE_PRICE = 'ERROR_RECEIVE_PRICE';

export const HIDE_API_ERROR = 'HIDE_API_ERROR';
