export const REQUEST_TIME_SERIES = 'REQUEST_TIME_SERIES';
export const RECEIVE_TIME_SERIES = 'RECEIVE_TIME_SERIES';
export const ERROR_RECEIVE_TIME_SERIES = 'ERROR_RECEIVE_TIME_SERIES';

export const HIDE_API_ERROR = 'HIDE_API_ERROR';
